### PR TITLE
Translation of Hack Club Site into Urdu

### PR DESCRIPTION
**Pull request by SyedHuzaifa007**
Hi There,

I have translated the Hack Club website into Urdu. Could you review the changes and merge the code? If there is any need for improvement, please feel free to mention it in the comments. 

Thanks.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/copy/ur**](https://around-the-globe-ri2z39ikc.hackclub.dev/copy/ur) |
|:-:|
|<a href="https://around-the-globe-ri2z39ikc.hackclub.dev/copy/ur">Screenshot of /copy/ur</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Nz0fXREQK9c6wNWSbkgLMc_gJyKIwUQTOGS2fdFuVQKEOgu6iOEhQF3xhndL3sT_WyoB3d-vOmM_veRldll9Wg.png">(view full size)</a> |







Commit a633e73029e1ce3a08710a3bcb270dc07546e648 (https://around-the-globe-ri2z39ikc.hackclub.dev).

**Comment by SyedHuzaifa007** [comment]
I've seen the preview of the page, It needs some punctuation correction let me do that.

**Comment by SyedHuzaifa007** [comment]
All done, This page can be given a specified domain now.

**Review by sampoder — APPROVED** [review]
This is awesome! Super appreciate it @SyedHuzaifa007!

**Pull request merged**
