### PR TITLE
Update the bengali translated version + add bn.hackclub.com to the readme

### PR DESCRIPTION
**Pull request by ni5arga**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/copy/bn**](https://around-the-globe-fehgu3exo.hackclub.dev/copy/bn) |
|:-:|
|<a href="https://around-the-globe-fehgu3exo.hackclub.dev/copy/bn">Screenshot of /copy/bn</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/v2SeP8cp4IZV4onNjHajmJ8ETTsUTFUTIA1F48hqKnMOnujgCO4qFkOsm8P21KkBa0QeTWMviVg1nL-YX0ZSGg.png">(view full size)</a> |







Commit 3437cb4aa43e60fcd664ee1b03d33d6b8eddfabf (https://around-the-globe-fehgu3exo.hackclub.dev).

**Comment by ni5arga** [comment]
I'll have to update the description, it's too short.

**Comment by ni5arga** [comment]
All done!

**Review by sampoder — APPROVED** [review]
Looks good! LGTM!

**Pull request merged**
