### PR TITLE
Make Better Korean Translation 

### PR DESCRIPTION
**Pull request by X3N064**
1. kr to ko according to ISO 639-1 of Korean Language.
2. better translation for Korean Language.

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/copy/ko**](https://around-the-globe-hxzf80xvq.hackclub.dev/copy/ko) |
|:-:|
|<a href="https://around-the-globe-hxzf80xvq.hackclub.dev/copy/ko">Screenshot of /copy/ko</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ejLYTx0OIzwffSw8Waf467dHGw8l4so2yX2K5Vaq6f_7S096tWd9q6om9rPq9LZgBUx8oqz2AoyQ1SiSEziNkA.png">(view full size)</a> |







Commit e83ba6d9eebeb2aa8a818de3dcf776f052017e84 (https://around-the-globe-hxzf80xvq.hackclub.dev).

**Comment by X3N064** [comment]
I have changed readme.md because OSI 639-1 of Korean Language is ko, not kr. Also changed kr to ko on /dns repo.

**Comment by JosiasAurel** [comment]
what about we allow both ko. & kr. so that things will not break for  people who may already be referencing kr.

**Comment by X3N064** [comment]
sure. I think that's a good idea.

**Comment by reesericci** [comment]
I just merged the change into DNS which has both ko and kr

**Comment by JosiasAurel** [comment]
@X3N064 please edit this PR to include both kr. and ko. in the markdown file

**Comment by JosiasAurel** [comment]
any updates here?

**Comment by JosiasAurel** [comment]
closing due to inactivity

**Pull request closed without merging**
